version: "3"
services:
  coopi:
    image: lmacka/coopi:latest
    container_name: coopi
    privileged: true
    volumes:
      - coopi_var:/coopi/var/
    ports:
      - "8086:8086"
    restart: always

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=600  # 10 minutes in seconds
    command: coopi
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./extras/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - coopi
    restart: always

volumes:
  coopi_var: