version: "3"
services:
  coopi:
    image: lmacka/coopi:latest
    container_name: coopi
    privileged: true
    volumes:
      - coopi_var:/coopi/var/
    ports:
      - "80:8086"
    restart: always

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=600  # 10 minutes in seconds
    command: coopi
    restart: unless-stopped

volumes:
  coopi_var: