version: "3.9"
services:
  coopi:
    image: lmacka/coopi:latest
    container_name: coopi
    privileged: true
    volumes:
      - coopi_var:/coopi/var/
    ports:
      - "80:80"
    command: gunicorn --bind 0.0.0.0:80 coopi.coopi:app
    restart: always

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: coopi watchtower --label-enable
    restart: unless-stopped

volumes:
  coopi_var: