version: '2.1'
services:
  main:
    build: .
    privileged: true
    environment:
      - TZ=Australia/Brisbane
    volumes:
      - coopi_data:/data
    ports:
      - "80:80"
    labels:
      io.balena.features.supervisor-api: '1'
      io.balena.features.kernel-modules: '1'
      io.balena.features.sysfs: '1'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: always

# Define named volumes with specific labels for Balena
volumes:
  coopi_data:
    driver: local