services:
  coopi:
    image: lmacka/coopi:latest
    container_name: coopi
    privileged: true
    environment:
      - TZ=Australia/Brisbane
      - VERSION=${VERSION:-v0.1.0}
    volumes:
      - coopi_var:/coopi/var/
    ports:
      - "80:80"
    command: gunicorn --bind 0.0.0.0:80 --timeout 120 coopi.coopi:app
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600 --label-enable
    restart: unless-stopped

volumes:
  coopi_var: