name: Pylint

on:
  push:
    paths:
      - '**.py'
      - 'requirements.txt'
      - '.github/workflows/pylint.yml'
  pull_request:
    paths:
      - '**.py'
      - 'requirements.txt'
      - '.github/workflows/pylint.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt
        # Install RPi.GPIO mock for CI environment
        pip install fake-rpi
    
    - name: Configure RPi.GPIO mock
      run: |
        echo "import sys" > /tmp/RPi.py
        echo "sys.modules['RPi'] = __import__('fake_rpi').RPi" >> /tmp/RPi.py
        echo "sys.modules['RPi.GPIO'] = __import__('fake_rpi').RPi.GPIO" >> /tmp/RPi.py
        export PYTHONPATH="/tmp:$PYTHONPATH"
    
    - name: Run pylint
      run: |
        pylint $(git ls-files '*.py') --fail-under=9.0